#!/bin/sh
#***************************************************************************
#                      tailer - start a tail process on a file
#                      -------------------------------
#    copyright         : (c)2001-2010 by Steve Gibson
#    email             : steve@stevegibson.com
#***************************************************************************

#***************************************************************************
#                                                                          *
#    This program is free software; you can redistribute it and/or modify  *
#    it under the terms of the GNU General Public License as published by  *
#    the Free Software Foundation; either version 2 of the License, or     *
#    (at your option) any later version.                                   *
#                                                                          *
#***************************************************************************

stat=1
pidfile=/tmp/tailer.$$
echo "$$" > $pidfile
trap 'echo "`basename $0`: exiting..." 1>&2;rm -f $pidfile;exit $stat' 0 1 2 15 
case $# in
	1) exec tail -f -n 25 "$1"
	   stat=0
	   ;;
	*) echo "usage: `basename $0` filename" 1>&2
	   ;;
esac
